// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCURg7yJfody2rgNb3gg0pgS4ewhsHtHY4',
    appId: '1:460276294412:web:deef710824baf0c8e61f29',
    messagingSenderId: '460276294412',
    projectId: 'notes-3b0c6',
    authDomain: 'notes-3b0c6.firebaseapp.com',
    storageBucket: 'notes-3b0c6.appspot.com',
    measurementId: 'G-2D5GYBZRKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQLmfz-Ud7MflaLOjmQDrmyNicHN5y3qg',
    appId: '1:460276294412:android:f993ee58e0c4e124e61f29',
    messagingSenderId: '460276294412',
    projectId: 'notes-3b0c6',
    storageBucket: 'notes-3b0c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVZGD5TUa5oNxLGUOvh6HItLatsACHpg',
    appId: '1:460276294412:ios:d1c01f1405a3fd65e61f29',
    messagingSenderId: '460276294412',
    projectId: 'notes-3b0c6',
    storageBucket: 'notes-3b0c6.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVZGD5TUa5oNxLGUOvh6HItLatsACHpg',
    appId: '1:460276294412:ios:d1c01f1405a3fd65e61f29',
    messagingSenderId: '460276294412',
    projectId: 'notes-3b0c6',
    storageBucket: 'notes-3b0c6.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCURg7yJfody2rgNb3gg0pgS4ewhsHtHY4',
    appId: '1:460276294412:web:c5836e12657d140fe61f29',
    messagingSenderId: '460276294412',
    projectId: 'notes-3b0c6',
    authDomain: 'notes-3b0c6.firebaseapp.com',
    storageBucket: 'notes-3b0c6.appspot.com',
    measurementId: 'G-FE090CWKWZ',
  );
}
